protocols = imap

log_path = /dev/stderr
auth_verbose = yes
ssl = no
listen = *
mail_location = maildir:/srv/mail/Maildir

passdb {
  driver = passwd-file
  args = scheme=PLAIN username_format=%u /etc/dovecot/users
}

userdb {
  driver = passwd-file
  args = username_format=%u /etc/dovecot/users
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}

auth_mechanisms = plain login
disable_plaintext_auth = no
first_valid_uid = 1000
